# Base constants for the game
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SMALL_MULTIPLIER = 0.25
ASTEROID_MEDIUM_MULTIPLIER = 0.5
ASTEROID_LARGE_MULTIPLIER = 1

# Player
PLAYER_RADIUS = 20
PLAYER_SPEED = 400
PLAYER_ROTATION_SPEED = 250
PLAYER_VELOCITY_DECAY = 0.99

# Bullets
BULLET_RADIUS = 2
BULLET_SPEED = 3
BULLET_LIFETIME = 1  # seconds